name: Run Danger
inputs:
  github-token: 
    description: GitHub access token for Danger
    required: true

on:
  pull_request:
    types: [opened, synchronize, reopened]

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download SwiftLint config
      run: curl -O https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/.swiftlint.yml
      shell: bash

    - name: Download Dangerfile
      run: curl -O https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/Dangerfile.swift
      shell: bash

    - name: Run Danger
      env:
        GITHUB_TOKEN: github-token
      run: |
       docker run --rm \
          -e GITHUB_ACTIONS=true
          -v "${{ github.workspace }}:/workspace" \
          ghcr.io/danger/danger-swift-with-swiftlint:3.15.0 \
          danger-swift ci --dangerfile="/workspace/Dangerfile.swift" --config="/workspace/.swiftlint.yml" --fail-on-errors
      shell: bash
