#!/bin/sh
commitMessageRegex="^v\d+\.\d+ \| \[\w+-\d+\] (feature|bug|refactor|test|other): .*"
commitMessageFile="$1"

if [ -z "$commitMessageFile" ]; then
  echo "Error: No commit message file provided."
  exit 1
fi

commitMessage=$(cat "$commitMessageFile")

if ! echo "$commitMessage" | grep -qE "$commitMessageRegex"; then
  echo "Commit message does not match the required format"
  exit 1
fi

userEmailRegex="@eightpoint\.io$"
userEmail=$(git config user.email)

if ! [[ "$userEmail" =~ $userEmailRegex ]]; then
  echo "Invalid commit author email"
  exit 1
fi