#!/bin/sh
commitMessageRegex="^v\d+\.\d+ \| \[\w+-\d+\] (feature|bug|refactor|test|other): .*"
commitMessage="$1"

if ! echo "$commitMessage" | grep -qE "$commitMessageRegex"; then
  echo "Commit message '${commitMessage}' does not match the required format"
  exit 1
fi

userEmailRegex="@eightpoint\.io$"
userEmail="$2"

if ! echo "$userEmail" | grep -qE "$userEmailRegex"; then
  echo "Invalid commit author email '${userEmail}'"
  exit 1
fi

branchNameRegex="(^\w+\-\d+-.*|^main$)"
branchName="$3"

if ! echo "$branchName" | grep -qE "$branchNameRegex"; then
  echo "Invalid branch name '${branchName}'"
  exit 1
fi