#!/bin/sh
commitMessageRegex="^v\d+\.\d+ \| \[\w+-\d+\] (feature|bug|refactor|test|other): .*"
commitMessage="$1"

if ! echo "$commitMessage" | grep -qE "$commitMessageRegex"; then
  echo "Commit message does not match the required format"
  exit 1
fi

userEmailRegex="@eightpoint\.io$"
userEmail="$2"

if ! echo "$userEmail" | grep -qE "$userEmailRegex"; then
  echo "Invalid commit author email"
  exit 1
fi