name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SwiftLint config
        run: curl -o ".swiftlint.yml" https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/.swiftlint.yml

      - name: Download Dangerfile
        run: curl -o "Dangerfile.swift" https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/Dangerfile.swift

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
        run: danger-swift ci --fail-on-errors

