name: Dismiss Pull Request Approvals

on:
  push:
    branches:
      - '*'

jobs:
  dismiss_approvals:
    runs-on: ubuntu-latest

    steps:
    - name: Check If remote head is PR
      id: check_pr
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pulls } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`,
            state: 'open'
          });

          if (pulls.length > 0) {
            core.setOutput('is_pr', true);
            core.setOutput('pr_number', pulls[0].number);
          } else {
            core.setOutput('is_pr', false);
          }

    - name: Dismiss Approvals
      if: steps.check_pr.outputs.is_pr == 'true'
      uses: actions/github-script@v6
      env:
        ACTION_API_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
      with:
        pr_number: ${{ steps.check_pr.outputs.pr_number }}
        script: |
          const { execSync } = require('child_process');

          const repo = context.repo.repo;
          const token = process.env.ACTION_API_TOKEN;
          const pr_number = core.getInput('pr_number');
          
          const getReviewsURL = `https://api.github.com/repos/EightpointIO/${repo}/pulls/${pr_number}/reviews`;
          const reviewsData = execSync(`curl --location "${getReviewsURL}" -H "Authorization: Bearer ${token}"`);
          const reviewsJSON = JSON.parse(reviewsData);
          const approvedReviewsIDs = reviewsJSON
            .map(review => review.state == "APPROVED" ? review.id : null)
            .filter(review => review);

          approvedReviewsIDs.forEach(reviewID => { 
            const dismissReviewURL = `https://api.github.com/repos/EightpointIO/${repo}/pulls/${pr_number}/reviews/${reviewID}/dismissals`;
            execSync(`curl --location --request PUT ${dismissReviewURL} -H "Authorization: Bearer ${token}" -d '{"event": "DISMISS", "message":"There is a new commit, please review the changes."}'`);
          });
