name: CI/CD Pipeline
on:
  workflow_call:
    inputs:
      TEAM_NAME:
        required: true
        type: string
      TESTS_SCHEME_NAME:
        required: false
        type: string
      SIMULATOR:
        required: false
        type: string
        default: 'iPhone 16'
      SIMULATOR_OS:
        required: false
        type: string
        default: '18.2'
      XCODE_VERSION:
        required: false
        type: string
        default: 'latest'

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Add author as the assignee
      uses: actions/github-script@v6
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const pr_number = context.payload.pull_request.number;
          const pr_author = context.payload.pull_request.user.login;

          await github.rest.issues.addAssignees({
            owner: owner,
            repo: repo,
            issue_number: pr_number,
            assignees: [pr_author]
          });

    - name: Add reviewers
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
      with:
        script: |
          const { execSync } = require('child_process');

          const repo = context.repo.repo;
          const pr_number = context.payload.pull_request.number;
          const pr_author = context.payload.pull_request.user.login;
          const token = process.env.GITHUB_TOKEN;
          
          const membersData = execSync(`curl --location "https://api.github.com/orgs/EightpointIO/teams/${{ inputs.TEAM_NAME }}/members" -H "Authorization: Bearer ${token}"`);
          const membersJSON = JSON.parse(membersData);
          const logins = membersJSON
            .map(member => JSON.stringify(member.login))
            .filter(login => login != JSON.stringify(pr_author) && login != "ios-devops");

          execSync(`curl --location "https://api.github.com/repos/EightpointIO/${repo}/pulls/${pr_number}/requested_reviewers" -H "Authorization: Bearer ${token}" -d '{"reviewers":[${logins}]}'`);

  notify_on_slack:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    steps:
    - name: Send notification to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MEMBERS: ${{ secrets.SLACK_MEMBERS }}
      run: |
        PR_URL="${{ github.event.pull_request.html_url }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_OWNER="${{ github.event.pull_request.user.login }}"
        REPO_NAME="${{ github.repository }}"
        REPO_NAME=${REPO_NAME#EightpointIO/}

        SLACK_MEMBER_ID=$(echo "$SLACK_MEMBERS" | jq -r --arg owner "$PR_OWNER" '.[$owner]')

        if [ "$SLACK_MEMBER_ID" != "null" ]; then
          SLACK_MESSAGE_PREFIX="<@$SLACK_MEMBER_ID> has opened a new PR in"
        else
          SLACK_MESSAGE_PREFIX="A new PR has been opened in"
        fi

        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"🚀 <!here> ${SLACK_MESSAGE_PREFIX} *${REPO_NAME}*: *<${PR_URL}|${PR_TITLE}>*\"
        }" $SLACK_WEBHOOK_URL

  check_pr_quality:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    container:
      image: ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SwiftLint config
        run: curl -o ".swiftlint.yml" https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/.swiftlint.yml

      - name: Download Dangerfile
        run: curl -o "Dangerfile.swift" https://raw.githubusercontent.com/EightpointIO/ios-build-public/refs/heads/main/Dangerfile.swift

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
        run: danger-swift ci --fail-on-errors

  dismiss_stale_approvals:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'synchronize' }}
    steps:
    - name: Dismiss Approvals
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        script: |
          const { execSync } = require('child_process');

          const repo = context.repo.repo;
          const token = process.env.GITHUB_TOKEN;
          const pr_number = context.payload.pull_request.number;
          
          const getReviewsURL = `https://api.github.com/repos/EightpointIO/${repo}/pulls/${pr_number}/reviews`;
          const reviewsData = execSync(`curl --location "${getReviewsURL}" -H "Authorization: Bearer ${token}"`);
          const reviewsJSON = JSON.parse(reviewsData);
          const approvedReviewsIDs = reviewsJSON
            .map(review => review.state == "APPROVED" ? review.id : null)
            .filter(review => review);

          approvedReviewsIDs.forEach(reviewID => { 
            const dismissReviewURL = `https://api.github.com/repos/EightpointIO/${repo}/pulls/${pr_number}/reviews/${reviewID}/dismissals`;
            execSync(`curl --location --request PUT ${dismissReviewURL} -H "Authorization: Bearer ${token}" -d '{"event": "DISMISS", "message":"There is a new commit, please review the changes."}'`);
          });

          if (approvedReviewsIDs.length > 0) {
            const pr_url = context.payload.pull_request.html_url;
            const pr_title = context.payload.pull_request.title;
            const slack_webhook_url = process.env.SLACK_WEBHOOK_URL;
            
            const message = {
              text: `ℹ <!here> A new commit has been pushed to *PR<${pr_url}|#${pr_number}>* in *${repo}* and approvals have been dismissed. Please review the changes: <${pr_url}|${pr_title}>`
            };

            execSync(`curl -X POST -H "Content-type: application/json" --data '${JSON.stringify(message)}' ${slack_webhook_url}`);
          }
    
  run_unit_tests:
    runs-on: macOS-latest
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened') && inputs.TESTS_SCHEME_NAME != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.XCODE_VERSION }}
          
      - name: Configure SPM to use HTTPS with token
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_API_TOKEN }}
        run: |
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"

      - name: Run Unit Tests
        run: |
          xcodebuild test -scheme ${{ inputs.TESTS_SCHEME_NAME }} -destination "platform=iOS Simulator,name=${{ inputs.SIMULATOR }},OS=${{ inputs.SIMULATOR_OS }}"
          if [ $? -ne 0 ]; then
            echo "Tests for ${{ inputs.TESTS_SCHEME_NAME }} failed!"
            exit 1
          fi
